-- 00_copy_into_raw.sql
-- Purpose: Load CSV data into RAW schema using Snowflake COPY INTO

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE OR REPLACE TABLE RAW.RAW_ORDERS (
  ORDER_ID NUMBER,
  ORDER_DATE DATE,
  CUSTOMER_ID NUMBER,
  PRODUCT_ID NUMBER,
  QUANTITY NUMBER,
  UNIT_PRICE NUMBER(10,2),
  UPDATED_AT TIMESTAMP_NTZ
);

-- Create internal stage
CREATE OR REPLACE STAGE RAW.ORDERS_STAGE;

-- Upload file via SnowSQL or UI:
-- PUT file://orders_sample.csv @RAW.ORDERS_STAGE;

-- Load data
COPY INTO RAW.RAW_ORDERS
FROM @RAW.ORDERS_STAGE
FILE_FORMAT = (
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
);
