-- 01_raw_to_staging.sql
-- Purpose: Create schemas and move data from RAW to STAGING using MERGE for incremental loads

-- Schemas (edit if needed)
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;

-- Example RAW table (landing)
CREATE TABLE IF NOT EXISTS RAW.RAW_ORDERS (
  ORDER_ID        NUMBER,
  ORDER_DATE      DATE,
  CUSTOMER_ID     NUMBER,
  PRODUCT_ID      NUMBER,
  QUANTITY        NUMBER,
  UNIT_PRICE      NUMBER(10,2),
  UPDATED_AT      TIMESTAMP_NTZ
);

-- STAGING table (cleaned + de-duplicated)
CREATE TABLE IF NOT EXISTS STAGING.STG_ORDERS (
  ORDER_ID        NUMBER,
  ORDER_DATE      DATE,
  CUSTOMER_ID     NUMBER,
  PRODUCT_ID      NUMBER,
  QUANTITY        NUMBER,
  UNIT_PRICE      NUMBER(10,2),
  UPDATED_AT      TIMESTAMP_NTZ,
  LOAD_TS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Incremental upsert from RAW to STAGING
MERGE INTO STAGING.STG_ORDERS tgt
USING (
  SELECT
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    UPDATED_AT
  FROM RAW.RAW_ORDERS
) src
ON tgt.ORDER_ID = src.ORDER_ID
WHEN MATCHED AND src.UPDATED_AT > tgt.UPDATED_AT THEN UPDATE SET
  ORDER_DATE  = src.ORDER_DATE,
  CUSTOMER_ID = src.CUSTOMER_ID,
  PRODUCT_ID  = src.PRODUCT_ID,
  QUANTITY    = src.QUANTITY,
  UNIT_PRICE  = src.UNIT_PRICE,
  UPDATED_AT  = src.UPDATED_AT,
  LOAD_TS     = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  ORDER_ID, ORDER_DATE, CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, UPDATED_AT
) VALUES (
  src.ORDER_ID, src.ORDER_DATE, src.CUSTOMER_ID, src.PRODUCT_ID, src.QUANTITY, src.UNIT_PRICE, src.UPDATED_AT
);
