-- 02_dims.sql
-- Purpose: Build dimensions (example) from STAGING

CREATE SCHEMA IF NOT EXISTS DW;

-- Customer dimension (example)
CREATE TABLE IF NOT EXISTS DW.DIM_CUSTOMER (
  CUSTOMER_ID NUMBER PRIMARY KEY,
  CUSTOMER_NAME VARCHAR,
  UPDATED_AT TIMESTAMP_NTZ,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Product dimension (example)
CREATE TABLE IF NOT EXISTS DW.DIM_PRODUCT (
  PRODUCT_ID NUMBER PRIMARY KEY,
  PRODUCT_NAME VARCHAR,
  UPDATED_AT TIMESTAMP_NTZ,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- NOTE:
-- In real life, DIM tables come from customer/product sources.
-- Here we simulate dims from STG_ORDERS for portfolio/demo.

MERGE INTO DW.DIM_CUSTOMER tgt
USING (
  SELECT DISTINCT
    CUSTOMER_ID,
    'Customer ' || CUSTOMER_ID AS CUSTOMER_NAME,
    MAX(UPDATED_AT) OVER (PARTITION BY CUSTOMER_ID) AS UPDATED_AT
  FROM STAGING.STG_ORDERS
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
WHEN MATCHED AND src.UPDATED_AT > tgt.UPDATED_AT THEN UPDATE SET
  CUSTOMER_NAME = src.CUSTOMER_NAME,
  UPDATED_AT    = src.UPDATED_AT,
  LOAD_TS       = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (CUSTOMER_ID, CUSTOMER_NAME, UPDATED_AT)
VALUES (src.CUSTOMER_ID, src.CUSTOMER_NAME, src.UPDATED_AT);

MERGE INTO DW.DIM_PRODUCT tgt
USING (
  SELECT DISTINCT
    PRODUCT_ID,
    'Product ' || PRODUCT_ID AS PRODUCT_NAME,
    MAX(UPDATED_AT) OVER (PARTITION BY PRODUCT_ID) AS UPDATED_AT
  FROM STAGING.STG_ORDERS
) src
ON tgt.PRODUCT_ID = src.PRODUCT_ID
WHEN MATCHED AND src.UPDATED_AT > tgt.UPDATED_AT THEN UPDATE SET
  PRODUCT_NAME = src.PRODUCT_NAME,
  UPDATED_AT   = src.UPDATED_AT,
  LOAD_TS      = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (PRODUCT_ID, PRODUCT_NAME, UPDATED_AT)
VALUES (src.PRODUCT_ID, src.PRODUCT_NAME, src.UPDATED_AT);
