-- 03_facts.sql
-- Purpose: Build a fact table from STAGING

CREATE SCHEMA IF NOT EXISTS DW;

CREATE TABLE IF NOT EXISTS DW.FACT_ORDERS (
  ORDER_ID NUMBER PRIMARY KEY,
  ORDER_DATE DATE,
  CUSTOMER_ID NUMBER,
  PRODUCT_ID NUMBER,
  QUANTITY NUMBER,
  UNIT_PRICE NUMBER(10,2),
  ORDER_AMOUNT NUMBER(12,2),
  UPDATED_AT TIMESTAMP_NTZ,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO DW.FACT_ORDERS tgt
USING (
  SELECT
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    (QUANTITY * UNIT_PRICE) AS ORDER_AMOUNT,
    UPDATED_AT
  FROM STAGING.STG_ORDERS
) src
ON tgt.ORDER_ID = src.ORDER_ID
WHEN MATCHED AND src.UPDATED_AT > tgt.UPDATED_AT THEN UPDATE SET
  ORDER_DATE    = src.ORDER_DATE,
  CUSTOMER_ID   = src.CUSTOMER_ID,
  PRODUCT_ID    = src.PRODUCT_ID,
  QUANTITY      = src.QUANTITY,
  UNIT_PRICE    = src.UNIT_PRICE,
  ORDER_AMOUNT  = src.ORDER_AMOUNT,
  UPDATED_AT    = src.UPDATED_AT,
  LOAD_TS       = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  ORDER_ID, ORDER_DATE, CUSTOMER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, ORDER_AMOUNT, UPDATED_AT
) VALUES (
  src.ORDER_ID, src.ORDER_DATE, src.CUSTOMER_ID, src.PRODUCT_ID, src.QUANTITY, src.UNIT_PRICE, src.ORDER_AMOUNT, src.UPDATED_AT
);
